= cache
:!toc-title:
:!toc-placement:
:toc:

Setup a cache using AWS Elasticache. Valkey is the default engine, which is a drop-in replacement for Redis >= 7.2.
Read more https://aws.amazon.com/elasticache/what-is-valkey/[about valkey here].

This module is an upgrade from the previous https://github.com/nsbno/terraform-aws-redis[`terraform-aws-redis` module].

toc::[]

== Usage

Remember to check out the link:variables.tf[*variables*] and link:outputs.tf[*outputs*] to see all options.

[source,hcl]
----
module "elasticache" {
  source = "github.com/nsbno/terraform-aws-cache?ref=x.y.z"

  service_name       = "my-cool-train-status-thingy"
  security_group_ids = [aws_security_group.this.id]

  vpc_id     = data.aws_vpc.main.id
  subnet_ids = data.aws_subnet_ids.private.ids
}
----

== High Availability

The `availability_zones` variable decides if the cluster is spun up in high availability.

If it is set up, it will set up the amount of nodes needed to match the AZs and enable automatic failover.

== Access

Only the given `security_group_ids` can access the cluster.

If you want to grant additional services access to the cluster, make sure to either add them to the list or manually grant access using the `security_group_id` output.
